# Numpy

In [44]:
import numpy as np

## numpy array
data struktur mirip List tapi bukan List, bisa handle data tipe numerik

CRUD - create read update delete

In [45]:
# create numpy array

#bikin dari list
nilai = [100,50,70,60,43]
arr = np.array(nilai)

print(nilai, type(nilai))
print()
print("np.array")
print(arr, type(arr))

[100, 50, 70, 60, 43] <class 'list'>

np.array
[100  50  70  60  43] <class 'numpy.ndarray'>


In [46]:
# kalau list nya 2 dimensi, numpy array juga jadi 2 dimensi
nilai = [[100,5],[70,60],[43, 88]]
arr = np.array(nilai)

print(nilai, type(nilai))
print()
print("np.array")
print(arr, type(arr))

#note: jumlah item di setiap dimensi harus sama, misalkan ada 3 baris, maka di setiap baris jumlah itemnya sama
# semuanya 2, semuanya 1, semuanya 10, bebas ada berapa tapi harus sama jumlahnya

[[100, 5], [70, 60], [43, 88]] <class 'list'>

np.array
[[100   5]
 [ 70  60]
 [ 43  88]] <class 'numpy.ndarray'>


In [47]:
# bikin dari built-in function Numpy
# zeros - array isi angka 0
# ones - array isi angka 1
# empty - array kosong, ada isi angka tapi anggap saja kosong

arr = np.zeros(10)
print("np.zeros")
print(arr, type(arr))
print()

arr = np.ones(10)
print("np.ones")
print(arr, type(arr))
print()

arr = np.empty(5)
print("np.empty")
print(arr, type(arr))
print()

np.zeros
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] <class 'numpy.ndarray'>

np.ones
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] <class 'numpy.ndarray'>

np.empty
[9.54898106e-312 7.42698527e-312 5.30498948e-312 3.18299369e-312
 1.06099790e-312] <class 'numpy.ndarray'>



In [48]:
arr = np.zeros((3, 4))
print("np.zeros")
print(arr, type(arr))
print()

arr = np.ones((4, 3))
print("np.ones")
print(arr, type(arr))
print()

arr = np.empty((5, ))
print("np.empty")
print(arr, type(arr))
print()

#*note: yang kita masukin adalah shape nya dalam bentuk tuple

np.zeros
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] <class 'numpy.ndarray'>

np.ones
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] <class 'numpy.ndarray'>

np.empty
[9.54898106e-312 7.42698527e-312 5.30498948e-312 3.18299369e-312
 1.06099790e-312] <class 'numpy.ndarray'>



In [49]:
# isi angka urut, np.arange

arr = np.arange(5)
print("np.arange")
print(arr, type(arr))
print()


arr = np.arange(5, 15)
print("np.arange")
print(arr, type(arr))
print()


arr = np.arange(500, 0, -50)
print("np.arange")
print(arr, type(arr))
print()

np.arange
[0 1 2 3 4] <class 'numpy.ndarray'>

np.arange
[ 5  6  7  8  9 10 11 12 13 14] <class 'numpy.ndarray'>

np.arange
[500 450 400 350 300 250 200 150 100  50] <class 'numpy.ndarray'>



In [50]:
# kita bisa juga pakai bantuan reshape untuk buat numpy array 2D

arr = np.arange(500, 0, -50).reshape((2,5))
print("np.arange")
print(arr, type(arr))
print()



np.arange
[[500 450 400 350 300]
 [250 200 150 100  50]] <class 'numpy.ndarray'>



In [51]:
# isi angka random, np.random.random

arr = np.random.random(15)
print("np.random.random")
print(arr, type(arr))
print()

np.random.random
[0.16432554 0.15936195 0.88352431 0.15695539 0.53536593 0.66608351
 0.66187946 0.56666838 0.83473019 0.4482607  0.26073901 0.97237501
 0.82543297 0.67719163 0.22120289] <class 'numpy.ndarray'>



In [52]:
arr = np.random.random(15).reshape((3,5))
print("np.random.random")
print(arr, type(arr))
print()

np.random.random
[[0.78444323 0.55148459 0.79324381 0.11222231 0.92138929]
 [0.90427474 0.60730918 0.50401679 0.50447633 0.39881906]
 [0.30156559 0.75633762 0.08934852 0.31313135 0.29131912]] <class 'numpy.ndarray'>



In [53]:
# perbedaan list dan numpy array kalau dikali atau di tambah
nilai = [100, 5, 70, 60, 43, 88]

arr_nilai = np.array(nilai)

print(arr_nilai + 3)


[103   8  73  63  46  91]


In [54]:
# kita bisa gunakan np.random.random dan sifat numpy array yang langsung ubah angka kalau dikasih aritmatik
# untuk membuat dummy data. misalkan dummy data buang dua dadu 20 sisi sebanyak 100 kali:

hasil_dadu1 = (np.random.random(100) * 20 + 1).astype(int)
hasil_dadu2 = (np.random.random(100) * 20 + 1).astype(int)
hasil_dadu = hasil_dadu1 + hasil_dadu2
hasil_dadu

array([30, 24, 22, 10, 21, 16, 15, 33, 32, 32, 30, 23, 18, 20, 31, 28, 34,
       14, 17, 17, 25, 15, 23, 14, 22, 15, 28, 21, 20,  8, 21, 24,  9, 21,
       20, 21, 32, 22, 31, 19,  5, 23,  7, 17, 29,  6, 28, 15, 25, 17, 29,
       18, 34, 33, 23, 12, 39, 29, 12,  9, 23, 18, 13, 39, 19, 16, 13, 35,
       33, 18, 25, 14,  8, 12, 22,  7,  5, 15, 13, 14, 28, 17, 25, 19, 11,
       16, 25, 24, 24, 16, 13, 32,  8, 19, 17, 16, 15, 19,  2, 20])

In [55]:
# read numpy array

print(arr)

[[0.78444323 0.55148459 0.79324381 0.11222231 0.92138929]
 [0.90427474 0.60730918 0.50401679 0.50447633 0.39881906]
 [0.30156559 0.75633762 0.08934852 0.31313135 0.29131912]]


In [56]:
# cara sama seperti list, pakai index
arr[1]

array([0.90427474, 0.60730918, 0.50401679, 0.50447633, 0.39881906])

In [57]:
# melihat bentuk, jumlah angka, dan dimensi sebuah array

print(arr.shape)

(3, 5)


In [58]:
print(arr.ndim)

2


In [59]:
print(arr.size)

15


In [60]:
# contoh numpy array 2 dimensi

arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [61]:
print(arr.shape)
print(arr.ndim)
print(arr.size)

(2, 3)
2
6


In [63]:
# edit numpy array

# aritmatik + - * / % **

# dengan 1 angka
print(arr)
print(arr + 10)
print(arr - 6)
print(arr * 2)
print(arr / 3)
print(arr % 2) # pembagian yang ambil sisanya saja, misal 5 % 2, sisanya adalah 1
print(arr ** 3)



[[1 2 3]
 [4 5 6]]
[[11 12 13]
 [14 15 16]]
[[-5 -4 -3]
 [-2 -1  0]]
[[ 2  4  6]
 [ 8 10 12]]
[[0.33333333 0.66666667 1.        ]
 [1.33333333 1.66666667 2.        ]]
[[1 0 1]
 [0 1 0]]
[[  1   8  27]
 [ 64 125 216]]


In [65]:
# dengan numpy array lain

arr2 = np.arange(6,0,-1).reshape((2,3))
print(arr)
print(arr2)
print()

print(arr + arr2)
print(arr - arr2)
print(arr * arr2)
print(arr / arr2)
print(arr % arr2)
print(arr ** arr2)

[[1 2 3]
 [4 5 6]]
[[6 5 4]
 [3 2 1]]

[[7 7 7]
 [7 7 7]]
[[-5 -3 -1]
 [ 1  3  5]]
[[ 6 10 12]
 [12 10  6]]
[[0.16666667 0.4        0.75      ]
 [1.33333333 2.5        6.        ]]
[[1 2 3]
 [1 1 0]]
[[ 1 32 81]
 [64 25  6]]


In [70]:
# teknik built-in numpy array
# sum, mean (rata2), max, min, std (nanti di kelas), ...

print(arr)
print(arr.sum())
print(arr.mean())
print(arr.max())
print(arr.min())

[[1 2 3]
 [4 5 6]]
21
3.5
6
1


In [72]:
# kalau mau hitung sum, mean (rata2), max, min, ... per baris atau per kolom juga bisa
penjualan = np.array([  [10, 12,  9, 15],
                        [ 5,  9,  7,  6],
                        [20,  2, 15, 30]])

print(penjualan.mean(axis=0)) # membandingkan dimensi pertama, baris ke baris

[11.66666667  7.66666667 10.33333333 17.        ]


In [73]:
print(penjualan.mean(axis=1)) # membandingkan dimensi kedua, kolom ke kolom

[11.5   6.75 16.75]


# matrix 
matrix adalah numpy array 2 dimensi

## dot product 
memerlukan dua matrix yang shape nya terbalik, misalkan:
- matrix pertama shape (3,6) maka matrix kedua shape nya (6,3)

In [71]:
# matrix profit
profit = np.array([[2800, 4500, 4800]])

# matrix penjualan
penjualan = np.array([  [10, 12,  9, 15],
                        [ 5,  9,  7,  6],
                        [20,  2, 15, 30]])

# hitung profit
profit_per_hari = profit.dot(penjualan)
profit_per_minggu = profit_per_hari.sum()
print(profit_per_hari)
print(profit_per_minggu)

[[146500  83700 128700 213000]]
571900


In [74]:
# mau hitung total profit 4 hari bisa pakai sum()

# Indexing dan Slicing
indexing = ambil 1 item pakai index

slicing = ambil bbrp item pakai index juga

In [75]:
print(penjualan)

[[10 12  9 15]
 [ 5  9  7  6]
 [20  2 15 30]]


In [80]:
# lihat penjualan srikaya di hari kamis
# baris ketiga 2
# kolom ke empat 3
penjualan[2,3]

30

In [76]:
# semua baris :
# kolom pertama 0
penjualan[:, 0]

array([10,  5, 20])

In [79]:
# dua baris pertama 0:2
# kolom kedua dan ketiga 1:3
penjualan[0:2, 1:3]

array([[12,  9],
       [ 9,  7]])

# Query
mengambil item pakai kondisi

In [82]:
print(penjualan)

[[10 12  9 15]
 [ 5  9  7  6]
 [20  2 15 30]]


In [83]:
# misal mau ambil yang lebih dari 10 saja
# selain > bisa juga pakai komparator lain < >= <= != ==
kondisi = penjualan > 10

print(kondisi)

[[False  True False  True]
 [False False False False]
 [ True False  True  True]]


In [84]:
penjualan[kondisi]

array([12, 15, 20, 15, 30])

In [85]:
penjualan[penjualan > 10]

array([12, 15, 20, 15, 30])

In [87]:
kumpulan_index = np.array([ [False,  True, False,  True],
                            [False, False, False, False],
                            [ True, False,  True,  True]   ])

penjualan[kumpulan_index]

array([12, 15, 20, 15, 30])

In [88]:
# query bisa banyak kondisi, pakai and dan or juga bisa
print(penjualan)

[[10 12  9 15]
 [ 5  9  7  6]
 [20  2 15 30]]


In [90]:
# mau yang penjualan diatas 5 dan angka ganjil
kondisi1 = penjualan > 5
kondisi2 = (penjualan % 2 == 1)

penjualan[kondisi1 & kondisi2]

array([ 9, 15,  9,  7, 15])

In [91]:
penjualan[(penjualan > 5) & (penjualan % 2 == 1)]

array([ 9, 15,  9,  7, 15])

In [92]:
# mau penjualan diatas 10 atau angka genap
kondisi1 = penjualan > 10
kondisi2 = (penjualan % 2 == 0)

penjualan[kondisi1 | kondisi2]

array([10, 12, 15,  6, 20,  2, 15, 30])

In [93]:
penjualan[(penjualan > 10) | (penjualan % 2 == 0)]

array([10, 12, 15,  6, 20,  2, 15, 30])

# copy
numpy array mirip list, kalau kita masukin ke variable lain, kayak cuman dapat nama baru, numpy array jadi punya dua nama

kalau kita pakai copy, maka jadinya ada dua numpy array

In [95]:
penjualan2 = penjualan

In [96]:
penjualan2[0,0] = 0

In [97]:
print(penjualan2)

[[ 0 12  9 15]
 [ 5  9  7  6]
 [20  2 15 30]]


In [98]:
print(penjualan)

[[ 0 12  9 15]
 [ 5  9  7  6]
 [20  2 15 30]]


In [99]:
# kita bisa bikin duplikat dengan pakai copy

penjualan_copy = penjualan.copy()

In [100]:
penjualan_copy[0,0] = 50

In [101]:
print(penjualan_copy)

[[50 12  9 15]
 [ 5  9  7  6]
 [20  2 15 30]]


In [102]:
print(penjualan)

[[ 0 12  9 15]
 [ 5  9  7  6]
 [20  2 15 30]]


# transpose
berbeda dengan reshape, transpose memastikan teman sebaris jadi teman sekolom setelah di transpose

In [104]:
print(penjualan)

[[ 0 12  9 15]
 [ 5  9  7  6]
 [20  2 15 30]]


In [105]:
print(penjualan.T)

[[ 0  5 20]
 [12  9  2]
 [ 9  7 15]
 [15  6 30]]


In [106]:
print(penjualan.reshape((4,3)))

[[ 0 12  9]
 [15  5  9]
 [ 7  6 20]
 [ 2 15 30]]
